[[main]]
name = 'Home'
pageRef = '/'
weight = 10

[[main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[main]]
name = "Series"
pageRef = "/series"
weight = 30

[[main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

