name = "Jules' Hugo Theme"
license = 'MIT'
licenselink = 'https://github.com/LeftySolara/Jules-Hugo-Theme/blob/master/LICENSE'
description = "Julianne's custom Hugo theme."

# The home page of the theme, where the source can be found
homepage = 'https://github.com/LeftySolara/Jules-Hugo-Theme'

# If you have a running demo of the theme
# demosite = ''

# Taxonomy terms
tags = ['blog']
features = []

# If the theme has a single author
[author]
  name = 'Julianne Adams'
  homepage = 'https://julianneadams.dev'
